server:
  port: ${PORT:8085}

spring:
  application:
    name: sudoku-master-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:sudokudb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  # SMTP Mail Configuration
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:bhanuprakash.gandham12@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:sbijvjhkpfrxznzd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET:9A7885F6E324B32D157A8E719548A9C2B1D3E5F7A9B0C2D4E6F8A1C3E5G7I9K1}
  expirationMs: 86400000
